python: "2.7"
before_script:
  - sudo apt-get install python-mock
  - git clone https://github.com/vim-jp/vital.vim /tmp/vital.vim
  - git clone https://github.com/thinca/vim-themis /tmp/vim-themis
script:
  - pip freeze
  - vim -u NONE -i NONE -N  --cmd "py import sys;print sys.path; import mock" --cmd quit
